/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IPoolInterface extends ethers.utils.Interface {
  functions: {
    "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;

  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;

  events: {};
}

export class IPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPoolInterface;

  functions: {
    "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _maxCap: BigNumberish,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(address,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)"(
    _token: string,
    _maxCap: BigNumberish,
    _duration: BigNumberish,
    _openTime: BigNumberish,
    _offeredCurrency: string,
    _offeredCurrencyDecimals: BigNumberish,
    _offeredRate: BigNumberish,
    _walletAddress: string,
    _signer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(address,uint256,uint256,address,uint256,uint256,address,address)"(
    _token: string,
    _duration: BigNumberish,
    _openTime: BigNumberish,
    _offeredCurrency: string,
    _offeredCurrencyDecimals: BigNumberish,
    _offeredRate: BigNumberish,
    _walletAddress: string,
    _signer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _maxCap: BigNumberish,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _maxCap: BigNumberish,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(address,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    "initialize(address,uint256,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _maxCap: BigNumberish,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address,uint256,uint256,address,uint256,uint256,address,address)"(
      _token: string,
      _duration: BigNumberish,
      _openTime: BigNumberish,
      _offeredCurrency: string,
      _offeredCurrencyDecimals: BigNumberish,
      _offeredRate: BigNumberish,
      _walletAddress: string,
      _signer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
